### ISSUE TITLE
How to Install

### ISSUE THREAD

**Issue by abhisek-kundu** [AamirRaihan/SWAT#1]
I am trying to install SWAT package using pytorch 1.3.1, pytorch 1.4 (and latest versions) but facing the following error.

hello-extension.cpp:174:10: error: could not convert ‘out’ from ‘std::tuple<at::Tensor, at::Tensor, at::Tensor, at::Tensor>’ to ‘std::tuple<at::Tensor, at::Tensor, at::Tensor>’
   return out;
          ^~~

It seems like it is a pytorch version error. Please let me know how to install it properly.
Thanks

**Comment by abhisek-kundu** [comment]
The following install solved the above problem
pip install torch==1.3.1+cu100 torchvision==0.6.2+cu100 -f https://download.pytorch.org/whl/torch_stable.html

however,
I am facing the following error while running 
python main.py --model 'resnet18' --dataset 'cifar10' --schedule-file resnet_schedule.yaml

ImportError:
/lib/python3.7/site-packages/mypkg-0.0.0-py3.7-linux-x86_64.egg/mypkg.cpython-37m-x86_64-linux-gnu.so: undefined symbol: _ZN2at6native16getCudnnDataTypeERKNS_6TensorE

**Comment by AamirRaihan** [comment]
Please install torch version 1.1.1 and then you won't get the error. Pytorch has internal modify the cuDNN wrapper module and therefore you are getting this error. For easily replicating the code you can also use the docker image I have created: https://hub.docker.com/r/swaticml/custom-swat-pytorch 

![image](https://user-images.githubusercontent.com/32428715/101805808-0a8fd280-3ac8-11eb-8759-fe077ad273fa.png)

**Comment by AamirRaihan** [comment]
Let me know if you get any more errors in replicating the experiment. I will update it in the instruction which I will be releasing soon.

**Comment by abhisek-kundu** [comment]
We tried various version of Pytorch but could not resolve the issue. Can you please provide detail instructions for installation without docker? Please mention the versions of python, cuda, g++ etc

**Comment by AamirRaihan** [comment]
```bash 
# GCC Version  5.5.0 20171010

# Install CUDA-10.0.130 
wget https://developer.nvidia.com/compute/cuda/10.0/Prod/local_installers/cuda_10.0.130_410.48_linux
./cuda_10.0.130_410.48_linux

# Install cuDNN-/cudnn-7.6.4.38 
wget https://developer.nvidia.com/compute/machine-learning/cudnn/secure/7.6.4.38/Production/10.0_20190923/cudnn-10.0-linux-x64-v7.6.4.38.tgz
cp libcudnn.so  cuda-10/lib64/
cp cudnn.h   cuda-10/include/

# Install the anaconda enabled with Python 3.7.4
wget https://repo.anaconda.com/archive/Anaconda3-2019.10-Linux-x86_64.sh
./Anaconda3-2019.10-Linux-x86_64.sh

# Install Pytorch
 conda install pytorch==1.1.0 torchvision==0.3.0 cudatoolkit=10.0 -c pytorch

# Clone the SWAT Repository
git clone https://github.com/AamirRaihan/SWAT.git

cd SWAT/SWAT-code/mypkg
python setup.py install ```

**Comment by AamirRaihan** [comment]
You should be able to run the SWAT code by following the above guideline. It has lots of version-specific dependencies therefore, for easily replicating the experiment I created the docker image.

**Comment by alexmaraval** [comment]
Hi, is there a way to use SWAT with a more recent version of `torch` and `torchvision` ? The versions you mention in your guide are now a little bit outdated
