### ISSUE TITLE
Code about pruning activations during backward

### ISSUE THREAD

**Issue by Nusselder9** [AamirRaihan/SWAT#3]
Hi!

Thanks for your cool work. The results are so awesome.
Could you please tell me where is the code of 'structured pruning activations during backward'? Thank you very much!

**Comment by AamirRaihan** [comment]
Hi @Nusselder9 ,

Thanks. Structured swat performs **L1 sparsification on weights** during forward and backward pass such that the final trained network has structured sparsity on weights i.e. model we obtained after structured pruning. 

Structured SWAT does not perform structured activations pruning during  backward pass. Experimentally, I have observed it is detrimental to convergence accuracy.
